{% if @('app.build') == 'static' %}
FROM {{ @('docker.repository') ~ ':' ~ @('app.version') }}-console as console
{% endif %}

FROM nginx:1.19-alpine
COPY root /

{% if @('app.build') == 'static' %}
{% for copy_directory in @('nginx.copy_directories')|filter(v => v is not empty) %}
COPY --from=console {{ copy_directory }} {{ copy_directory }}
{% endfor %}
{% else %}
VOLUME /app
{% endif %}

ENTRYPOINT ["sh", "/docker-entrypoint.d/config_render.sh"]
CMD ["nginx", "-g", "daemon off;"]
