apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: php-fpm
  name: php-fpm
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    app.service: php-fpm
status:
  loadBalancer: {}
