FROM {{ @('docker.image.console') }}
# fix upstream signal
STOPSIGNAL SIGTERM

{% for service in [@('services.redis'), @('services.redis-session')] | filter(v => v.enabled) | slice(0, 1) %}
# copy the redis-cli from the first enabled redis service image
COPY --from={{ service.image }} /usr/local/bin/redis-cli /usr/local/bin/redis-cli
{% endfor %}

COPY .my127ws/docker/image/console/root /
RUN chown -R build:build /home/build /app \
 && curl --fail --silent --location --output /sbin/tini https://github.com/krallin/tini/releases/download/v0.19.0/tini \
 && chmod +x /sbin/tini \
 && curl --fail --silent --location --output /usr/local/bin/mhsendmail https://github.com/mailhog/mhsendmail/releases/download/v0.2.0/mhsendmail_linux_amd64 \
 && chmod +x /usr/local/bin/mhsendmail \
 && mkdir -p /tmp/php-file-cache \
 && chown -R build:build /tmp/php-file-cache
{%- if @('php.composer.major_version') != '1' %} \
 && composer self-update --{{ @('php.composer.major_version') }} \
 && rm -f /root/.composer/*.phar
{%- endif %}
{%- set install_extensions=@('php.install_extensions')|merge(@('php.cli.install_extensions'))|filter(v => v is not empty) %}
{%- if install_extensions %} \
 && cd /root/installer \
 && ./enable.sh \
    {{ install_extensions|join(" \\\n    ") }}
{% endif %}

ENV APP_MODE={{ @('app.mode') }} \
  APP_BUILD={{ @('app.build') }} \
  ASSETS_DIR={{ @('assets.local') }}
{%- set extra_environment_variables=@('services.console.build.environment')|filter(v => v is not empty) %}
{%- if extra_environment_variables %}
{%- for name, value in extra_environment_variables %} \
  {{ name }}="{{ value }}"
{% endfor %}
{% endif %}

USER build

{% if @('node.version') is not null %}
RUN . /home/build/.nvm/nvm.sh \
 && nvm install {{ @('node.version') }} \
 && nvm use {{ @('node.version') }} \
 && nvm alias default {{ @('node.version') }} \
 && npm install -g yarn
{% endif %}

{% if @('php.composer.major_version') != '1' %}
RUN composer --no-plugins global remove hirak/prestissimo
{% endif %}

{% if @('app.build') == 'static' %}
COPY --chown=build:build .my127ws/application  /home/build/application
COPY --chown=build:build ./                    /app
RUN app build
{% else %}
VOLUME /app
VOLUME /home/build/application
{% endif %}

USER root

{% if version_compare(@('php.ext-xdebug.version'), '3', '>=') and version_compare(@('php.version'), '7', '>=') and version_compare(@('php.version'), '8', '<') %}
RUN pecl -q upgrade xdebug
{% endif %}

RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sleep", "infinity"]
