attributes:
  spryker:
    mode: 'production'
  namespace: =exec("git log -n 1 --pretty=format:'%H'")
  hostname: =@('workspace.name') ~ '.' ~ @('domain')
  app:
    build: static
    mode: production
    version: =exec("git log -n 1 --pretty=format:'%H'")
