
attributes:
  spryker:
    mode: 'production'
  namespace: =@('workspace.name') ~ '-' ~ exec("git rev-parse --short HEAD")
  hostname: =@('workspace.name') ~ '.' ~ @('domain')
  app:
    build: static
    version: =exec("git log -n 1 --pretty=format:'%H'")
    mode: production
  php:
    fpm:
      ini:
        display_errors: Off
        zend.assertions: -1
    ini:
      opcache.validate_timestamps: Off
      error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
