os:
  - linux
sudo: required
language: php
php:
  - 7.2
services:
  - docker
env:
  # drupal8
  - HARNESS=drupal8 MODE=static
  - HARNESS=drupal8 MODE=dynamic
  # magento1
  - HARNESS=magento1 MODE=static
  - HARNESS=magento1 MODE=dynamic
  # magento2
  - HARNESS=magento2 MODE=static
  - HARNESS=magento2 MODE=dynamic
  # wordpress
  - HARNESS=wordpress MODE=static
  - HARNESS=wordpress MODE=dynamic
install:
  # worksace
  - wget https://my127.io/workspace/ws && chmod +x ws && sudo mv ws /usr/local/bin/ws
  # splitsh-lite
  - wget https://github.com/splitsh/lite/releases/download/v1.0.1/lite_linux_amd64.tar.gz
  - sudo tar -zxpf lite_linux_amd64.tar.gz --directory /usr/local/bin/
script:
  - ./build
  # dynamic
  - cp -ap dist/harness-${HARNESS}/.ci/sample-${MODE} ./test && cd test && cp -ap ../dist/harness-${HARNESS} ./.my127ws
  - ws install
  - ws disable
  - ws enable
  - ws destroy
  - cd .. && rm -rf test
