#!/bin/bash

set -e
set -x

function usage() {
    cat <<EOF
$0 [--archive]
EOF
}

HARNESSES=(akeneo drupal magento1 magento2 spryker symfony wordpress)
ARCHIVE=0
ARGS=()

while [ $# -ne 0 ]; do
  case "$1" in
    --help)
      usage
      exit 0
      ;;
    --archive)
      ARCHIVE=1
      ;;
    *)
      ARGS+=("$1")
  esac
  shift 1
done


function main()
{
    build_base

    for harness in "${HARNESSES[@]}"
    do
        build "$harness"
        if [ "$ARCHIVE" -gt 0 ]; then
            archive "$harness"
        fi
    done

    if [ "$ARCHIVE" -gt 0 ]; then
        archive "php"
    fi
}

function build()
{
    local harness="$1"

    if [[ ! -d "$harness" ]]; then
        echo "harness '${harness}' not found."
    fi

    local harness_dist_path="./dist/harness-${harness}/"
    local harness_src_path="./src/${harness}/"

    if [[ -d "$harness_dist_path" ]]; then
        rm -rf "$harness_dist_path"
    fi

    mkdir "$harness_dist_path"

    rsync -va "./src/_base/" "$harness_dist_path"
    rsync -va "$harness_src_path" "$harness_dist_path"
}

function build_base()
{
    local harness_dist_path="./dist/harness-php/"
    local harness_src_path="./src/_base/"

    if [[ -d "$harness_dist_path" ]]; then
        rm -rf "$harness_dist_path"
    fi

    mkdir "$harness_dist_path"

    rsync -va "./src/_base/" "$harness_dist_path"
}

function archive()
{
    pushd ./dist >/dev/null

    tar -czvf "./harness-$1.tgz" "./harness-$1"
    rm -rf "./harness-$1"

    popd >/dev/null
}

main
