#!/bin/bash

set -e
set -x

HARNESSES=(akeneo)

function main()
{
    local BRANCH_NAME="$1"
    if [[ "$BRANCH_NAME" == "" ]]; then
        echo "error: please provide a branch name to push to" >&2
        exit 1
    fi
    if [[ "$BRANCH_NAME" =~ /^\d+\.\d+\.[0-9x]+$/ ]]; then
        echo "error: can't push to a tag-like branch-name" >&2
        exit 1
    fi

    if ! command -v splitsh-lite >/dev/null; then
        echo "error: splitsh-lite is needed to be installed first" >&2
        exit 1
    fi

    git checkout -b _build

    build

    for harness in "${HARNESSES[@]}"
    do
        set_remote "$harness" "git@github.com:inviqa/harness-${harness}.git"
        splitsh-lite --prefix="src/${harness}" --target="publish/harness-${harness}"
        git push -q -f "$harness" "publish/harness-${harness}:${BRANCH_NAME}"
    done

    git checkout "${BRANCH_NAME}"
    git branch -D _build
}

function set_remote()
{
    local name="$1"
    local path="$2"

    if ! git ls-remote --exit-code "$name" &>/dev/null; then
        git remote add "$name" "$path"
    fi
}

function build()
{
    for harness in "${HARNESSES[@]}"
    do
        rsync -va --ignore-existing "./src/_base/" "./src/$harness"
        git add .
        git commit -m "publish '${harness}' harness"
    done
}

main "$1"
