#!/bin/bash

set -e
set -x

HARNESSES=(drupal8 magento1 magento2 wordpress)

function main()
{
    git checkout -b _build

    build

    for harness in "${HARNESSES[@]}"
    do
        set_remote "$harness" "git@github.com:inviqa/harness-${harness}.git"
        splitsh-lite --prefix="src/${harness}" --target="publish/harness-${harness}"
        git push -q -f "$harness" "publish/harness-${harness}:0.2.x"
    done

    git checkout 0.2.x
    git branch -D _build
}

function set_remote()
{
    local name="$1"
    local path="$2"

    if ! git ls-remote --exit-code "$name" &>/dev/null; then
        git remote add "$name" "$path"
    fi
}

function build()
{
    for harness in "${HARNESSES[@]}"
    do
        rsync -va --ignore-existing "./src/_base/" "./src/$harness"
        git add .
        git commit -m "publish '${harness}' harness"
    done
}

main
