#!/bin/bash

function test()
{
    if [ "$HARNESS" = "spryker" ]; then
        ws exec composer phpstan
        # some default spryker tests are failing as well, not sure if we can run this in default build
        # probably this can be enabled at project level after fixing those failing tests?
        # ws exec vendor/bin/codecept run
    else
        ws exec composer test-quality
        ws exec composer test-unit
        ws exec composer test-acceptance
    fi
}

test
