#!/bin/bash

set -e
set -x

function main()
{
    test "$1" "$2"
}

function test()
(
    local harness="$1"
    local mode="$2"

    local path_harness="./dist/harness-${harness}"
    local path_test="./tmp-test"

    if [ -d "${path_test}" ]; then
        rm -rf "${path_test}"
    fi

    cp -ap "${path_harness}/.ci/sample-${mode}" "${path_test}"
    cd "${path_test}"
    cp -ap "../${path_harness}" "./.my127ws"

    ws install

    if [ "$(docker-compose -p "ci-${harness}-sample" ps | grep -c Exit)" -gt 0 ]; then
      echo 'Some containers failed to start'
      docker-compose -p "ci-${harness}-sample" ps
      return 1
    fi

    if [ -f composer.json ]; then
      ws exec composer test-quality
      ws exec composer test-unit
      ws exec composer test-acceptance
    fi

    ws helm template qa >/dev/null

    ws disable
    ws enable
)

function clean()
{
    local path_test="./tmp-test"

    if [ -d "$path_test" ]; then
        (cd "$path_test" && ws destroy)
        rm -rf "$path_test"
    fi
}

trap 'clean' EXIT
main "$@"
