{{- $service := include "service.resolved" (dict "root" $ "service_name" "console") | fromYaml -}}
{{ template "service.environment.secret" (dict "service_name" "console" "service" $service "root" $) }}
