{{ if and .Values.persistence.elasticsearch.enabled .Values.services.elasticsearch.enabled -}}

{{- with .Values.persistence.elasticsearch -}}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.resourcePrefix }}elasticsearch-pv-claim
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
    app.service: {{ $.Values.resourcePrefix }}elasticsearch
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .storageClass | quote }}
{{- end }}
{{- end }}
{{- with (pick . "selector" "volumeMode" "volumeName") }}
  {{- . | toYaml | nindent 2 }}
{{- end }}

{{- end }}

{{- end }}
