apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.service: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: nginx
  template:
    metadata:
      labels:
        app.service: nginx
    spec:
      containers:
      - image: {{ .Values.docker.image.nginx }}
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory.nginx }}
          requests:
            memory: {{ .Values.resources.requests.memory.nginx }}
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: docker-config
      restartPolicy: Always
status: {}
