{{ if eq .Values.ingress "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-auth-auth-virtualservice
 labels:
   app: auth
   app.service: auth
spec:
 hosts:
 - {{ .Values.environment.APP_HOST }}
 gateways:
 - istio-system/{{ .Release.Namespace }}-gateway
 http:
 - route:
   - destination:
       host: nginx
       port:
         number: 80
{{ end }}
