apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.prefix }}nginx
  name: {{ .Values.prefix }}nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Values.prefix }}nginx
status:
  loadBalancer: {}
