
attributes:
  namespace: =exec("git log -n 1 --pretty=format:'%H'")
  hostname: =@('workspace.name') ~ '.' ~ @('domain')
  app:
    build: static
    version: =exec("git log -n 1 --pretty=format:'%H'")
