FROM {{ @('docker.image.console') }}

# Install jq tool
# ----------------------------
RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && mkdir -p /usr/share/man/man1 \
 && mkdir -p /usr/share/man/man7 \
 && apt-get update -qq \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq -y --no-install-recommends install \
 jq \
 # clean \
 && apt-get auto-remove -qq -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY .my127ws/docker/image/console/root /
RUN chown -R build:build /home/build

ENV APP_MODE={{ @('app.mode') }} \
  ASSETS_DIR={{ @('assets.local') }}

{% if @('node.version') is not null %}
USER build
RUN . /home/build/.nvm/nvm.sh \
 && nvm install {{ @('node.version') }} \
 && nvm use {{ @('node.version') }} \
 && nvm alias default {{ @('node.version') }} \
 && npm install -g yarn
USER root
{% endif %}

{% if @('app.build') == 'static' %}
RUN chown build:build /app
COPY --chown=build:build .my127ws/application  /home/build/application
COPY --chown=build:build ./                    /app
USER build
RUN app build
USER root
{% else %}
VOLUME /app
VOLUME /home/build/application
{% endif %}

ENTRYPOINT /entrypoint.sh
