
command('app publish'): |
  #!bash(workspace:/)|@
  echo "@('docker.password')" | run docker login --user name="@('docker.username')" --password-stdin @('docker.repository')
  run docker-compose push console php-fpm nginx jenkins-runner
  run docker logout @('docker.repository')
