{{ if .Values.service.elasticsearch }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app.service: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: elasticsearch
  template:
    metadata:
      labels:
        app.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xmx512m -Xms512m
        - name: discovery.type
          value: single-node
        image: elasticsearch:5.6
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
status: {}
{{ end }}
