{{ if .Values.service.elasticsearch }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    app.service: elasticsearch
status:
  loadBalancer: {}
{{ end }}
