{{ if .Values.service.redis }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prefix }}redis-pv-claim
  labels:
    app.service: {{ .Values.prefix }}redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{ end }}
