apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.service: nginx
  name: nginx
spec:
  rules:
  - host: {{ .Values.environment.APP_HOST }}
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
status:
  loadBalancer: {}
