{% if @('app.build') == 'static' %}
FROM {{ @('docker.repository') ~ ':' ~ @('app.version') }}-console as console
{% endif %}

FROM {{ @('docker.image.php-fpm') }}
WORKDIR /app
COPY root  /

{% if @('app.build') == 'static' %}
COPY --from=console --chown=root:root /app /app
RUN bash /fix_app_permissions.sh
{% else %}
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sleep", "infinity"]
{% else %}
ENTRYPOINT ["/entrypoint.dynamic.sh"]
CMD ["sleep", "infinity"]
{% endif %}
