{# build from php-fpm Dockerfile #}
{% include 'docker/image/php-fpm/Dockerfile.twig' %}

WORKDIR /app
COPY .my127ws/docker/image/job-queue-consumer/root /

{% if @('app.build') == 'static' %}
RUN bash /fix_app_permissions.sh
{% else %}
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sleep", "infinity"]
{% else %}
ENTRYPOINT ["/entrypoint.dynamic.sh"]
CMD ["sleep", "infinity"]
{% endif %}
