{% if @('app.build') == 'static' %}
FROM {{ @('docker.repository') ~ ':' ~ @('app.version') }}-php-fpm
{% else %}
FROM {{ @('workspace.name') ~ '-php-fpm:dev' }}
{% endif %}

WORKDIR /app
COPY .my127ws/docker/image/job-queue-consumer/root /

RUN mkdir -p /tmp/php-file-cache \
 && chown -R www-data:www-data /tmp/php-file-cache \
 && chmod +x /entrypoint.sh /entrypoint.dynamic.sh
{%- if @('app.build') == 'static' %} \
 && bash /fix_app_permissions.sh
{% endif %}

{% if @('app.build') == 'dynamic' %} \
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
ENTRYPOINT ["/entrypoint.sh"]
{% else %}
ENTRYPOINT ["/entrypoint.dynamic.sh"]
{% endif %}
CMD ["sleep", "infinity"]
