{% if @('app.build') == 'static' %}
FROM {{ @('docker.repository') ~ ':' ~ @('app.version') }}-php-fpm
{% else %}
FROM {{ @('workspace.name') ~ '-php-fpm:dev' }}
{% endif %}

WORKDIR /app
COPY .my127ws/docker/image/job-queue-consumer/root /

RUN mkdir -p /tmp/php-file-cache \
 && chown -R www-data:www-data /tmp/php-file-cache

{% if @('app.build') == 'static' %}
RUN bash /fix_app_permissions.sh
{% else %}
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["sleep", "infinity"]
{% else %}
ENTRYPOINT ["/entrypoint.dynamic.sh"]
CMD ["sleep", "infinity"]
{% endif %}
