{{ if .Values.service.varnish | default .Values.docker.services.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}varnish
  name: {{ .Values.resourcePrefix }}varnish
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Values.resourcePrefix }}varnish
status:
  loadBalancer: {}
{{ end }}
