{{ if .Values.services.varnish.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: varnish
    app.service: {{ .Values.resourcePrefix }}varnish
  name: {{ .Values.resourcePrefix }}varnish
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Values.resourcePrefix }}varnish
status:
  loadBalancer: {}
{{ end }}
