{{ template "service.environment.secret" (dict
    "service_name" "jenkins-runner"
    "service" (merge
      (index .Values.docker.services "jenkins-runner")
      (index .Values.docker.services "php-fpm")
    )
  ) }}
