{{- $service := mergeOverwrite (dict) (index .Values.docker.services "php-base") (index .Values.docker.services "jenkins-runner") -}}
{{ template "service.environment.secret" (dict "service_name" "jenkins-runner" "service" $service "root" $) }}
