{{- $service := include "service.resolved" (dict "root" $ "service_name" "jenkins-runner") | fromYaml -}}
{{ template "service.environment.secret" (dict "service_name" "jenkins-runner" "service" $service "root" $) }}
