{{ if .Values.service.mysql }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mysql
  name: mysql
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app.service: mysql
status:
  loadBalancer: {}
{{ end }}
