{{ if eq .Values.ingress.type "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-{{ .Values.resourcePrefix }}webapp-virtualservice
 labels:
   app: {{ .Values.resourcePrefix }}webapp
   app.service: {{ .Values.resourcePrefix }}webapp
spec:
 hosts:
 - {{ index .Values.docker.services "php-base" "environment" "APP_HOST" }}
 gateways:
{{- range $key, $value := .Values.istio.gateways }}
 - {{ tpl $value $ | quote }}
{{- end }}
{{- range $key, $value := .Values.istio.additionalGateways }}
 - {{ $value | quote }}
{{- end }}
 http:
 - route:
   - destination:
       host: {{ .Values.resourcePrefix }}{{ .Values.ingress.target_service }}
       port:
         number: 80
{{ end }}
