{{- with .Values.ingresses.webapp }}
{{- if and (index $.Values.services .target_service "enabled") (eq .type "istio") }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-webapp
{{- with .annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
{{- end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapp
    app: {{ $.Release.Name }}-webapp
    app.service: {{ $.Release.Name }}-webapp
spec:
  {{- with (.hosts | default (list (index $.Values.services "php-base" "environment" "APP_HOST"))) }}
  hosts:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- with (. | dig "istio" "gateways" nil) | default $.global.istio.gateways }}
  gateways:
  {{- range $key, $value := . }}
    - {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ print $.Release.Name "-" .target_service | quote }}
        port:
          number: 80
  {{- with (pick . "tls" "exportTo") }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
