apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.resourcePrefix }}webapp
  name: {{ .Values.resourcePrefix }}webapp
spec:
  ports:
  - name: http-80
    port: 80
    targetPort: 80
  selector:
    app.service: {{ .Values.resourcePrefix }}webapp
status:
  loadBalancer: {}
