{{ if eq .Values.ingress "istio" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: {{ .Release.Namespace }}-{{ .Values.resourcePrefix }}nginx-virtualservice
 labels:
   app: {{ .Values.resourcePrefix }}nginx
   app.service: {{ .Values.resourcePrefix }}nginx
spec:
 hosts:
{{- range $key, $value := .Values.docker.services.nginx.environment }}
 - {{ $value | quote }}
{{- end }}
 gateways:
 - istio-system/{{ .Release.Namespace }}-gateway
 http:
 - route:
   - destination:
       host: {{ .Values.resourcePrefix }}nginx
       port:
         number: 80
{{ end }}
