command('app build'):
  exec: |
    #!bash(workspace:/)|@
    ws app build console
    ws app build php-fpm
    ws app build nginx
command('app build console'):
  exec: |
    #!bash(workspace:/)|@
    passthru docker build -t @('docker.repository'):@('app.version')-console -f .my127ws/docker/image/console/Dockerfile .
command('app build php-fpm'):
  exec: |
    #!bash(harness:/docker/image/php-fpm)|@
    passthru docker build -t @('docker.repository'):@('app.version')-php-fpm .
command('app build nginx'):
  exec: |
    #!bash(harness:/docker/image/nginx)|@
    passthru docker build -t @('docker.repository'):@('app.version')-nginx .
