
confd('harness:/'):
  - { src: docker/image/console/Dockerfile }
  - { src: docker/image/console/root/lib/task/build/frontend.sh }
  - { src: docker/image/console/root/lib/task/build/backend.sh }
  - { src: docker/image/console/root/lib/task/init.sh }
  - { src: docker/image/console/root/lib/task/install.sh }
  - { src: docker/image/console/root/usr/local/etc/php/php.ini }
  - { src: docker/image/console/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: docker/image/nginx/Dockerfile }
  - { src: docker/image/nginx/root/etc/nginx/conf.d/default.conf }
  - { src: docker/image/nginx/root/etc/ssl/certs/app.crt }
  - { src: docker/image/nginx/root/etc/ssl/private/app.key }
  - { src: docker/image/php-fpm/Dockerfile }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/php.ini }
  - { src: docker/image/php-fpm/root/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini }
  - { src: application/overlay/Jenkinsfile }
  - { src: application/overlay/auth.json }
  - { src: application/overlay/.dockerignore, dst: workspace:/.dockerignore }
  - { src: application/skeleton/README.md }
  - { src: docker-compose.yml, dst: workspace:/docker-compose.yml }
  - { src: docker-sync.yml, dst: workspace:/docker-sync.yml }
