
after('harness.install'): |
  #!bash
  ws enable

after('harness.refresh'):
  env:
    COMPOSE_PROJECT: = @('namespace')
  exec: |
    #!bash(workspace:/)|@
    run docker-compose stop
    ws external-images pull
    passthru "docker-compose config --services | grep -v cron | grep -v jenkins-runner | grep -v job-queue-consumer | xargs docker-compose build"
    passthru "docker-compose config --services | grep -v cron | grep -v jenkins-runner | grep -v job-queue-consumer | xargs docker-compose up -d"
    run docker-compose up -d --build
