
after('harness.install'): |
  #!bash
  ws enable

after('harness.refresh'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    COMPOSE_PROJECT: = @('namespace')
  exec: |
    #!bash(workspace:/)|@
    run $COMPOSE_BIN stop
    ws external-images pull
    passthru "$COMPOSE_BIN config --services | grep -v cron | grep -v jenkins-runner | grep -v job-queue-consumer | xargs $COMPOSE_BIN build"
    passthru "$COMPOSE_BIN config --services | grep -v cron | grep -v jenkins-runner | grep -v job-queue-consumer | xargs $COMPOSE_BIN up -d"
    run $COMPOSE_BIN up -d --build
