
after('harness.install'): |
  #!bash
  ws enable

after('harness.refresh'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    COMPOSE_PROJECT: = @('namespace')
  exec: |
    #!bash(workspace:/)|@
    run $COMPOSE_BIN stop
    ws external-images pull
    run $COMPOSE_BIN up -d --build
