function('external_images', [services]): |
  #!php
  $upstreamImages = [];
  $excludeImages = ['scratch'];

  foreach ($services as $service) {
    if (count($service['upstream']) > 0) {
      $upstreamImages = array_merge($upstreamImages, $service['upstream']);
      if ($service['image']) {
        $excludeImages[] = $service['image'];
      }
    } else if ($service['image']) {
      $upstreamImages[] = [
        'image' => $service['image'],
        'platform' => $service['platform'],
      ];
    }
  }
  $externalImages = array_filter(
    $upstreamImages,
    function ($image) use ($excludeImages) {
      return !in_array($image['image'], $excludeImages);
    }
  );

  # workspace commands don't allow non-string types
  = json_encode($externalImages);

command('external-images config [--skip-exists] [<service>]'):
  env:
    IMAGES: = external_images(docker_service_images(@('docker.compose.bin'), input.argument('service')))
    SKIP_EXISTS: "= input.option('skip-exists') ? 1 : 0"
  exec: |
    #!php
    $exclude = [];
    if ($env['SKIP_EXISTS']) {
      $exclude = explode("\n", shell_exec('docker image ls -a --format \'{{ print .Repository ":" .Tag }}\''));
    }
    $include = json_decode($env['IMAGES'], true);
    $compose = ['version' => '3', 'services' => []];
    foreach ($include as $image) {
      if (!in_array($image['image'], $exclude)) {
        $compose['services'][str_replace(['/', ':'], '_', $image['image'])] = array_filter($image, function ($value) { return $value !== null; });
      }
    }
    echo \Symfony\Component\Yaml\Yaml::dump($compose, 100, 2);

command('external-images pull [<service>]'):
  env:
    COMPOSE_BIN: = @('docker.compose.bin')
    SERVICE: = input.argument('service')
  exec: |
    #!bash(workspace:/)|@
    CONF_ARGS=()
    if [ -n "${CI:-}" ] || [ -n "${BUILD_ID:-}" ]; then
      CONF_ARGS+=(--skip-exists)
    fi

    if [ -n "${SERVICE}" ]; then
      CONF_ARGS+=("$SERVICE")
    fi

    passthru "ws external-images config $(printf '%q ' "${CONF_ARGS[@]}") | $COMPOSE_BIN -f - pull"

command('external-images ls [--all]'):
  env:
    IMAGES: = external_images(docker_service_images(@('docker.compose.bin')))
    SHOW_REMOTE: "= input.option('all') ? 1 : 0"
  exec: |
    #!php
    $include = array_map(
      function ($image) {
        return $image['image'];
      },
      json_decode($env['IMAGES'], true)
    );
    if ($env['SHOW_REMOTE']) {
      $images = $include;
    } else {
      $all = explode("\n", shell_exec('docker image ls -a --format \'{{ print .Repository ":" .Tag }}\''));
      $images = array_intersect($include, $all);
    }

    if (count($images) > 0) {
      echo join("\n", $images)."\n";
    }

command('external-images rm [--force]'):
  env:
    FORCE: = boolToString(input.option('force'))
  exec: |
    #!bash(workspace:/)|@
    IMAGES=($(ws external-images ls))
    OPTS=()

    if [ "${FORCE}" = yes ]; then
      OPTS+=(--force)
    fi

    if [ "${#IMAGES[@]}" -gt 0 ]; then
      docker image rm "${OPTS[@]}" -- "${IMAGES[@]}"
    fi
