function('external_images', [services]): |
  #!php

  $upstreamImages = call_user_func_array(
    'array_merge',
    array_map(
      function ($service) {
        return $service['upstream'];
      },
      $services
    )
  );

  $externalImages = array_filter(
    $upstreamImages,
    function ($image) use ($services) {
      $serviceUpstreamImages = array_filter(
        $services,
        function ($service) use ($image) {
          return $service['image'] == $image;
        }
      );
      return count($serviceUpstreamImages) == 0;
    }
  );

  # workspace commands don't allow non-string types
  = join(' ', $externalImages);


command('external-images config'):
  env:
    IMAGES: = external_images(docker_service_images())
  exec: |
    #!php
    $compose = ['version' => '3', 'services' => []];
    foreach (explode(' ', $env['IMAGES']) as $image) {
      $compose['services'][str_replace(['/', ':'], '_', $image)] = ['image' => $image];
    }
    echo \Symfony\Component\Yaml\Yaml::dump($compose, 100, 2);

command('external-images pull'):
  env:
    BASE_IMAGES: = external_images(docker_service_images())
  exec: |
    #!bash(workspace:/)|@
    passthru 'ws external-images config | docker-compose -f - pull'
