function('php_fpm_exporter_scrape_url', [hostname, pools]): |
  #!php
  $text = join(
      ',',
      array_map(
        function ($pool) use ($hostname) {
          return 'tcp://' . $hostname .':' . $pool['port'] . '/status';
        },
        $pools
      )
    );
  = $text;
