function('get_mutagen_volume_names'): |
  #!php
  $volumeNames = [];

  if (file_exists('mutagen.yml')) {
    $configRaw = file_get_contents('mutagen.yml');
    $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

    if (isset($config['sync']))  {
      foreach (array_keys($config['sync']) as $syncName) {
        $volumeNames[] = $syncName . '-sync';
      }
    }
  }
  = $volumeNames;

function('get_mutagen_volume_containers'): |
  #!php
  $volumeContainers = [];

  if (file_exists('mutagen.yml')) {
    $configRaw = file_get_contents('mutagen.yml');
    $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

    if (isset($config['sync']))  {
      foreach ($config['sync'] as $syncConfig) {
        $parts = parse_url($syncConfig['beta']);
        $volumeContainers[] = $parts['host'];
      }
    }
  }
  = join("\n", array_unique($volumeContainers));

function('get_mutagen_volume_mappings'): |
  #!php
  $volumeMappings = [];

  if (file_exists('mutagen.yml')) {
    $configRaw = file_get_contents('mutagen.yml');
    $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

    if (isset($config['sync']))  {
      foreach ($config['sync'] as $syncName => $syncConfig) {
        $parts = parse_url($syncConfig['beta']);
        $volumeMappings[] = $parts['host'] . ':' . $syncName . '-sync:' . $parts['path'];
      }
    }
  }
  = join("\n", $volumeMappings);

function('get_mutagen_forward_names'): |
  #!php
  $forwardNames = [];

  if (file_exists('mutagen.yml')) {
    $configRaw = file_get_contents('mutagen.yml');
    $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

    if (isset($config['forward']))  {
      $forwardNames = array_keys($config['forward']);
    }
  }
  = join("\n", array_unique($forwardNames));

function('get_mutagen_sync_names'): |
  #!php
  $syncNames = [];

  if (file_exists('mutagen.yml')) {
    $configRaw = file_get_contents('mutagen.yml');
    $config = \Symfony\Component\Yaml\Yaml::parse($configRaw);

    if (isset($config['sync']))  {
      $syncNames = array_keys($config['sync']);
    }
  }
  = join("\n", array_unique($syncNames));

command('mutagen (start|stop|pause|resume)'):
  env:
    COMMAND: = input.command(2)
    CONTAINER_NAMES: = get_mutagen_volume_containers()
    FORWARD_NAMES: = get_mutagen_forward_names()
    SYNC_NAMES: = get_mutagen_sync_names()
    VOLUME_MAPPINGS: = get_mutagen_volume_mappings()
  exec: |
    #!bash(workspace:/)
    source .my127ws/harness/scripts/mutagen.sh "$COMMAND"

command('mutagen rm'):
  env:
    CONTAINER_NAMES: = get_mutagen_volume_containers()
    FORWARD_NAMES: = get_mutagen_forward_names()
    SYNC_NAMES: = get_mutagen_sync_names()
  exec: |
     #!bash(workspace:/)
     CONTAINER_NAMES=($CONTAINER_NAMES)
     passthru docker volume rm "${CONTAINER_NAMES[@]}"

command('switch (cached-volumes|delegated-volumes|mutagen)'):
  env:
    SYNC: = input.command(2)
    CONTAINER_NAMES: = get_mutagen_volume_containers()
  exec: |
    #!bash(workspace:/)|=
    run ws disable
    if [[ "$SYNC" = "delegated-volumes" ]]; then
      ws set delegated-volumes yes
      ws set mutagen no
    elif [[ "$SYNC" = "mutagen" ]]; then
      ws set delegated-volumes no
      ws set mutagen yes
    else
      ws set delegated-volumes no
      ws set mutagen no
    fi
    run ws harness prepare
    echo 'Bringing up the environment with the new setting'
    if [[ "$SYNC" = "mutagen" ]]; then
      passthru ws mutagen start
    else
      passthru ws mutagen stop
    fi
    passthru ws enable
    echo 'Done'
