command('feature xdebug version-sync'):
  description: Install xdebug version configured by "php.ext-xdebug.version" into running PHP containers
  env:
    XDEBUG_VERSION: = @('php.ext-xdebug.version')
    COMPOSE_BIN: = @('docker.compose.bin')
  exec: |
    #!bash(workspace:/)
    source .my127ws/harness/scripts/xdebug_version_sync.sh

command('feature xdebug (on|off)'):
  description: Enable XDebug for PHP-FPM (disables JIT)
  env:
    ATTR_KEY: 'php.ext-xdebug.enable'
    ATTR_VAL: = boolToString(input.command(3) == 'on')
  exec: |
    #!bash(workspace:/)|=
    ws set $ATTR_KEY $ATTR_VAL
    passthru ws service php-fpm restart
    echo 'Done'

command('feature xdebug cli (on|off)'):
  description: Enable XDebug for PHP CLI (disables JIT)
  env:
    ATTR_KEY: 'php.ext-xdebug.cli.enable'
    ATTR_VAL: = boolToString(input.command(4) == 'on')
  exec: |
    #!bash(workspace:/)|=
    ws set $ATTR_KEY $ATTR_VAL
    passthru ws console reload
    echo 'Done'
