{{ if .Values.service.jenkins }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}jenkins
  labels:
    app.service: {{ .Values.prefix }}jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ .Values.prefix }}jenkins
  template:
    metadata:
      labels:
        app.service: {{ .Values.prefix }}jenkins
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        image: jenkins:alpine
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory.jenkins }}
          requests:
            memory: {{ .Values.resources.requests.memory.jenkins }}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
status: {}
{{ end }}
