{{ if .Values.service.jenkins }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app.service: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: jenkins
  template:
    metadata:
      labels:
        app.service: jenkins
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        image: jenkins:alpine
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
status: {}
{{ end }}
