{{- with .Values.docker.services.jenkins -}}
{{- if $.Values.service.jenkins | default .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.resourcePrefix }}jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: jenkins
    app.service: {{ $.Values.resourcePrefix }}jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ $.Values.resourcePrefix }}jenkins
{{- if $.Values.persistence.jenkins.enabled }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.selectors" $ | nindent 8 }}
        app.kubernetes.io/component: jenkins
        app.service: {{ $.Values.resourcePrefix }}jenkins
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        image: {{ .image | quote }}
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: {{ $.Values.resources.memory.jenkins | default .resources.memory }}
          requests:
            memory: {{ $.Values.resources.memory.jenkins | default .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: home
          mountPath: /var/jenkins_home
      restartPolicy: Always
      volumes:
      - name: home
{{- if $.Values.persistence.jenkins.enabled }}
        persistentVolumeClaim:
          claimName: {{ $.Values.resourcePrefix }}jenkins-home
{{- else }}
        emptyDir: {}
{{- end }}
status: {}
{{- end }}
{{- end }}
