{{ if .Values.services.jenkins.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourcePrefix }}jenkins
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: jenkins
    app.service: {{ .Values.resourcePrefix }}jenkins
spec:
  ports:
  - name: http-8080
    port: 8080
    targetPort: 8080
  - name: tcp-50000
    port: 50000
    targetPort: 50000
  selector:
    app.service: {{ .Values.resourcePrefix }}jenkins
status:
  loadBalancer: {}
{{ end }}
