{{ if .Values.service.jenkins }}
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app.service: jenkins
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    app.service: jenkins
status:
  loadBalancer: {}
{{ end }}
