FROM base as job-queue-consumer

WORKDIR /app
COPY .my127ws/docker/image/app/root-job-queue-consumer /

RUN mkdir -p /tmp/php-file-cache \
 && chown -R www-data:www-data /tmp/php-file-cache \
 && chmod +x /entrypoint.sh /entrypoint.dynamic.sh
{%- if @('app.build') == 'static' %} \
 && bash /fix_app_permissions.sh
{% endif %}

{% if @('app.build') == 'dynamic' %} \
VOLUME /app
{% endif %}
ENV APP_MODE {{ @('app.mode') }}

{% if @('app.build') == 'static' %}
ENTRYPOINT ["/entrypoint.sh"]
{% else %}
ENTRYPOINT ["/entrypoint.dynamic.sh"]
{% endif %}
CMD ["sleep", "infinity"]
