{% include 'docker/image/app/Dockerfile.base.twig' %}
{% include 'docker/image/app/Dockerfile.php-fpm.twig' %}
{% include 'docker/image/app/Dockerfile.cron.twig' %}
{% include 'docker/image/app/Dockerfile.job-queue-consumer.twig' %}
