{{- $service := include "service.resolved" (dict "root" $ "service_name" "job-queue-consumer") | fromYaml -}}
{{ template "service.environment.secret" (dict "service_name" "job-queue-consumer" "service" $service "root" $) }}
