{{- with .Values.services.mongodb -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.resourcePrefix }}mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: mongodb
    app.service: {{ $.Values.resourcePrefix }}mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: {{ $.Values.resourcePrefix }}mongodb
{{- if $.Values.persistence.mongodb.enabled }}
  strategy:
    type: Recreate
{{- end }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" $ | nindent 8 }}
        app.kubernetes.io/component: mongodb
        app.service: {{ $.Values.resourcePrefix }}mongodb
    spec:
      containers:
      - env:
        {{- range $key, $value := (mergeOverwrite (dict) .environment .environment_dynamic) }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .environment_secrets }}
        envFrom:
          - secretRef:
              name: {{ $.Values.resourcePrefix }}mongodb
        {{- end }}
        image: {{ .image | quote }}
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: {{ .resources.memory }}
          requests:
            memory: {{ .resources.memory }}
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: data-db
          mountPath: /data/db
      restartPolicy: Always
      volumes:
      - name: data-db
{{- if $.Values.persistence.mongodb.enabled }}
        persistentVolumeClaim:
          claimName: {{ $.Values.resourcePrefix }}mongodb
{{- else }}
        emptyDir: {}
{{- end }}
status: {}
{{- end }}
{{- end }}
