FROM yukinying/chrome-headless-browser:latest

USER root

RUN apt update \
 && apt install -y bc jq

ENV NVM_DIR /home/build/.nvm
USER headless
RUN cd /home/build \
 && mkdir .nvm \
 && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
 && . /home/headless/.nvm/nvm.sh \
 && nvm install lts/dubnium \
 && n latest \
 && npm install -g lighthouse
USER root

{% if @('app.build') == 'static' %}
COPY root  /
RUN chown headless /app/run.sh
RUN chmod u+x /app/run.sh
{% else %}
VOLUME /app
{% endif %}

USER headless

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/app/run.sh"]
